/**
 * Umami Analytics API Service
 * Handles automatic website creation and stats fetching for SchoolPro SaaS tenants.
 */

const UMAMI_URL = process.env.NEXT_PUBLIC_UMAMI_URL || 'http://localhost:3001'
const UMAMI_USERNAME = process.env.UMAMI_ADMIN_USERNAME || 'admin'
const UMAMI_PASSWORD = process.env.UMAMI_ADMIN_PASSWORD || 'umami'

let cachedToken: string | null = null

/**
 * Authenticates with Umami and returns a JWT token.
 * Caches the token in memory to avoid repeated logins.
 */
export async function getUmamiToken(): Promise<string> {
  if (cachedToken) return cachedToken

  try {
    const res = await fetch(`${UMAMI_URL}/api/auth/login`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        username: UMAMI_USERNAME,
        password: UMAMI_PASSWORD
      })
    })

    if (!res.ok) {
      throw new Error(`Umami login failed: ${res.statusText}`)
    }

    const data = await res.json()
    cachedToken = data.token
    return data.token
  } catch (error) {
    console.error('Umami Auth Error:', error)
    throw error
  }
}

/**
 * Creates a new website profile in Umami for a given tenant.
 * Returns the unique website ID generated by Umami.
 */
export async function createUmamiWebsite(domain: string, name: string): Promise<string> {
  try {
    const token = await getUmamiToken()
    
    const res = await fetch(`${UMAMI_URL}/api/websites`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${token}`
      },
      body: JSON.stringify({
        domain,
        name
      })
    })

    if (!res.ok) {
      // If unauthorized, token might be expired. Clear cache and try again.
      if (res.status === 401) {
        cachedToken = null
        return createUmamiWebsite(domain, name)
      }
      throw new Error(`Umami create website failed: ${res.statusText}`)
    }

    const data = await res.json()
    return data.id // This is the umamiWebsiteId
  } catch (error) {
    console.error('Umami Create Website Error:', error)
    throw error
  }
}

/**
 * Fetches basic traffic stats for a specific website from Umami.
 * By default, fetches data for the last 7 days.
 */
export async function getUmamiStats(websiteId: string, days: number = 7) {
  try {
    const token = await getUmamiToken()
    
    const endAt = Date.now()
    const startAt = endAt - (days * 24 * 60 * 60 * 1000)

    const res = await fetch(`${UMAMI_URL}/api/websites/${websiteId}/stats?startAt=${startAt}&endAt=${endAt}`, {
      method: 'GET',
      headers: {
        'Authorization': `Bearer ${token}`
      }
    })

    if (!res.ok) {
      if (res.status === 401) {
        cachedToken = null
        return getUmamiStats(websiteId, days)
      }
      throw new Error(`Umami fetch stats failed: ${res.statusText}`)
    }

    return await res.json()
  } catch (error) {
    console.error('Umami Fetch Stats Error:', error)
    return null
  }
}
