import { auth } from "@/lib/auth";
import { db } from "@/lib/db";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { MapPin, Building2, PackageSearch, MessageSquare } from "lucide-react";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";
import { RfqStatusControl } from "./rfq-pipeline";

// Define an interface since we assume the schema is being generated by the backend agent
interface RfqSubmission {
  id: string;
  buyerName: string;
  buyerEmail: string;
  buyerPhone: string | null;
  companyName: string | null;
  country: string | null;
  productInterest: string;
  quantity: string | null;
  additionalMessage: string | null;
  status: string;
  createdAt: Date;
}

export default async function AdminRfqPage() {
  const session = await auth();
  
  // Resolve tenantId, taking impersonation into account if needed
  const cookieStore = await cookies();
  const impersonateSlug = cookieStore.get("impersonate-tenant")?.value;
  
  let tenantId = session?.user?.tenants?.[0]?.id;
  
  if (impersonateSlug) {
    const impersonatedTenant = await db.tenant.findUnique({
      where: { slug: impersonateSlug },
      select: { id: true }
    });
    if (impersonatedTenant) {
      tenantId = impersonatedTenant.id;
    }
  }

  if (!tenantId) {
    redirect("/admin");
  }

  // Fetch RFQs from database
  // Assuming the backend agent has added this model
  const rfqs = await (db as any).rfqSubmission.findMany({
    where: { tenantId },
    orderBy: { createdAt: "desc" },
  }) as RfqSubmission[];

  return (
    <div className="space-y-6 pb-10">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold tracking-tight">Request for Quotations</h1>
          <p className="text-muted-foreground mt-1 text-sm">
            Manage and respond to quotation requests from potential buyers.
          </p>
        </div>
      </div>

      {rfqs.length === 0 ? (
        <Card className="glass border-0 shadow-sm flex flex-col items-center justify-center py-20 text-center">
          <PackageSearch className="h-16 w-16 text-muted-foreground/30 mb-4" />
          <CardTitle className="text-xl mb-2">No RFQs Yet</CardTitle>
          <CardDescription>
            When customers submit a Request for Quotation from your website, they will appear here.
          </CardDescription>
        </Card>
      ) : (
        <div className="grid gap-6 md:grid-cols-2 xl:grid-cols-3">
          {rfqs.map((rfq) => (
            <Card key={rfq.id} className="glass border-0 shadow-sm hover:shadow-md transition-shadow">
              <CardHeader className="pb-4 border-b border-muted/50">
                <div className="flex justify-between items-start">
                  <div>
                    <CardTitle className="text-lg font-bold">{rfq.buyerName}</CardTitle>
                    <div className="text-sm text-muted-foreground">{rfq.buyerEmail}</div>
                  </div>
                  <RfqStatusControl id={rfq.id} initialStatus={rfq.status} />
                </div>
              </CardHeader>
              <CardContent className="pt-4 space-y-4">
                <div className="grid grid-cols-2 gap-y-4 text-sm">
                  {rfq.companyName && (
                    <div className="flex gap-2 text-muted-foreground">
                      <Building2 className="h-4 w-4 shrink-0" />
                      <span className="truncate">{rfq.companyName}</span>
                    </div>
                  )}
                  {rfq.country && (
                    <div className="flex gap-2 text-muted-foreground">
                      <MapPin className="h-4 w-4 shrink-0" />
                      <span className="truncate">{rfq.country}</span>
                    </div>
                  )}
                  <div className="flex gap-2 text-muted-foreground col-span-2">
                    <PackageSearch className="h-4 w-4 shrink-0" />
                    <span className="font-medium text-foreground">
                      {rfq.productInterest} {rfq.quantity ? `(${rfq.quantity})` : ""}
                    </span>
                  </div>
                </div>

                {rfq.additionalMessage && (
                  <div className="pt-4 border-t border-muted/30">
                    <div className="flex gap-2 mb-2">
                      <MessageSquare className="h-4 w-4 text-muted-foreground shrink-0" />
                      <span className="text-xs font-semibold text-muted-foreground uppercase tracking-wider">Message</span>
                    </div>
                    <p className="text-sm line-clamp-3 text-zinc-700 dark:text-zinc-300">
                      {rfq.additionalMessage}
                    </p>
                  </div>
                )}
                
                <div className="text-xs text-muted-foreground pt-2">
                  Received on {new Date(rfq.createdAt).toLocaleDateString()}
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}
